Homework for the first linear algebra class:
https://services.math.duke.edu/~bfitzpat/teaching/7903f18/hw/7903f18-digraphs-hw.pdf

Problem 1. Consider the following digraph:
![alt text](Desktop/school/digraph.png "Title")

(a) Find the incidence vectors and the incidence matrix for this digraph. Clearly label your
vectors and your matrix.

In [19]:
import numpy as np
incidenceVectors = {"a1": np.array([-1,1,0,0,0,0]),
                    "a2": np.array([0,-1,1,0,0,0]),
                    "a3": np.array([0,-1,0,1,0,0]),
                    "a4": np.array([0,0,-1,0,1,0]),
                    "a5": np.array([0,0,0,-1,1,0]),
                    "a6": np.array([0,0,0,0,-1,1]),
                    "a7": np.array([0,0,0,-1,0,1])}
for i, j in incidenceVectors.items():
    print("For arrow " + i + ", the incidence vector is:")
    print(np.column_stack([j]))
    
A = np.array([incidenceVectors["a1"],
             incidenceVectors["a2"],
             incidenceVectors["a3"],
             incidenceVectors["a4"],
             incidenceVectors["a5"],
             incidenceVectors["a6"],
             incidenceVectors["a7"]])
A = A.T
print("And the matrix A all together is:")
print(A)

For arrow a1, the incidence vector is:
[[-1]
 [ 1]
 [ 0]
 [ 0]
 [ 0]
 [ 0]]
For arrow a2, the incidence vector is:
[[ 0]
 [-1]
 [ 1]
 [ 0]
 [ 0]
 [ 0]]
For arrow a3, the incidence vector is:
[[ 0]
 [-1]
 [ 0]
 [ 1]
 [ 0]
 [ 0]]
For arrow a4, the incidence vector is:
[[ 0]
 [ 0]
 [-1]
 [ 0]
 [ 1]
 [ 0]]
For arrow a5, the incidence vector is:
[[ 0]
 [ 0]
 [ 0]
 [-1]
 [ 1]
 [ 0]]
For arrow a6, the incidence vector is:
[[ 0]
 [ 0]
 [ 0]
 [ 0]
 [-1]
 [ 1]]
For arrow a7, the incidence vector is:
[[ 0]
 [ 0]
 [ 0]
 [-1]
 [ 0]
 [ 1]]
And the matrix A all together is:
[[-1  0  0  0  0  0  0]
 [ 1 -1 -1  0  0  0  0]
 [ 0  1  0 -1  0  0  0]
 [ 0  0  1  0 -1  0 -1]
 [ 0  0  0  1  1 -1  0]
 [ 0  0  0  0  0  1  1]]


(b) Find the transpose AT of the incidence matrix A. What are the sizes of A and AT?

In [20]:
print("The transpose of AT is:")
print(A.T) #lol involution
print("The size of A is 6x7, and the size of AT is 7x6.")

The transpose of AT is:
[[-1  1  0  0  0  0]
 [ 0 -1  1  0  0  0]
 [ 0 -1  0  1  0  0]
 [ 0  0 -1  0  1  0]
 [ 0  0  0 -1  1  0]
 [ 0  0  0  0 -1  1]
 [ 0  0  0 -1  0  1]]
The size of A is 6x7, and the size of AT is 7x6.


(c) Determine the net flow through each node by computing a vector sum.

In [21]:
vectorSum = np.sum(A,axis=1)
print("The vector sum is:")
print(np.column_stack([vectorSum]))
print("Which means that...")
for i in range(len(vectorSum)):
    print("Node " + str(i+1) + " has a net flow of " + str(vectorSum[i]) + ".")

The vector sum is:
[[-1]
 [-1]
 [ 0]
 [-1]
 [ 1]
 [ 2]]
Which means that...
Node 1 has a net flow of -1.
Node 2 has a net flow of -1.
Node 3 has a net flow of 0.
Node 4 has a net flow of -1.
Node 5 has a net flow of 1.
Node 6 has a net flow of 2.


(d) Suppose we choose weights for each arrow as follows: a1 --> 0, a2 --> 1, a3 --> 2, a4 --> -1, a5 --> 0, a6 --> 1, a7 --> -3.  Compute the weighted net flow through each node by computing the appropriate linear
combination of the incidence vectors of the digraph.

In [22]:
for i in range(len(A)): #rows/nodes
    weightedNetFlow = 0
    for j in range(7): #columns/arrows
        print("For row " + str(i+1) + ", column " + str(j+1) + ", we have " + str(M[i,j]) + " scaled by " + str(weights[j]) + "...")
        weightedNetFlow += M[i,j] * weights[j]
    print("So the weighted net flow for node " + str(i+1) + " is " + str(weightedNetFlow) + ".")

For row 1, column 1, we have -1 scaled by 0...
For row 1, column 2, we have 0 scaled by 1...
For row 1, column 3, we have 0 scaled by 2...
For row 1, column 4, we have 0 scaled by -1...
For row 1, column 5, we have 0 scaled by 0...
For row 1, column 6, we have 0 scaled by 1...
For row 1, column 7, we have 0 scaled by -3...
So the weighted net flow for node 1 is 0.
For row 2, column 1, we have 1 scaled by 0...
For row 2, column 2, we have -1 scaled by 1...
For row 2, column 3, we have -1 scaled by 2...
For row 2, column 4, we have 0 scaled by -1...
For row 2, column 5, we have 0 scaled by 0...
For row 2, column 6, we have 0 scaled by 1...
For row 2, column 7, we have 0 scaled by -3...
So the weighted net flow for node 2 is -3.
For row 3, column 1, we have 0 scaled by 0...
For row 3, column 2, we have 1 scaled by 1...
For row 3, column 3, we have 0 scaled by 2...
For row 3, column 4, we have -1 scaled by -1...
For row 3, column 5, we have 0 scaled by 0...
For row 3, column 6, we have 0 s

(e) Set-up a linear combination to determine if it is possible to choose weights such that
the weighted net flow through the nodes is given by b = <2, 3, −62, 1, −6, 0>.

In [23]:
print("As a reminder, the matrix is:")
print(A)
print("And we're looking for <2, 3, -62, 1, -6, 0> = c1 * a1 + c2 * a2 + ... + c6 * a6.")
print("The vector sum is:")
print(np.column_stack([vectorSum]))
print("It turns out that since there's nothing we can weight the third row by that would output anything but zero, we don't have a linear combination that works.")

As a reminder, the matrix is:
[[-1  0  0  0  0  0  0]
 [ 1 -1 -1  0  0  0  0]
 [ 0  1  0 -1  0  0  0]
 [ 0  0  1  0 -1  0 -1]
 [ 0  0  0  1  1 -1  0]
 [ 0  0  0  0  0  1  1]]
And we're looking for <2, 3, -62, 1, -6, 0> = c1 * a1 + c2 * a2 + ... + c6 * a6.
The vector sum is:
[[-1]
 [-1]
 [ 0]
 [-1]
 [ 1]
 [ 2]]
It turns out that since there's nothing we can weight the third row by that would output anything but zero, we don't have a linear combination that works.


Problem 2. Let G be the digraph whose incidence matrix is:
![alt text](Desktop/school/matrix.png "Title")
Sketch G.
![alt text](Desktop/school/newdigraph.png "Title")